# Generated by Django 4.2.9 on 2024-01-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Users',
        ),
    ]
