# Generated by Django 4.2.9 on 2024-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='merital',
            new_name='material',
        ),
    ]
