# Generated by Django 4.2.9 on 2024-01-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_purpose_rename_merital_student_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.purpose'),
            preserve_default=False,
        ),
    ]
